In [44]:
import numpy as np 

In [ ]:
A list is a built-in data structure in Python.
It can hold elements of multiple data types (e.g., integers, strings, floats, etc.).

An array is part of the array module in Python.
It holds elements of a single data type (e.g., integers, floats).

In [45]:
list_ = [ '1' , '2' , '3', '4' , '5']

In [46]:
array_list = np.array(object = list_)

In [47]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [48]:
type(list_)

list

In [35]:
type(array_list)

numpy.ndarray

In [39]:
list = [ '1' , '2' , '3', '4' , '5']

In [40]:
array_list1 = np.array(object = list)

In [41]:
array_list1

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [42]:
type(list)

list

In [43]:
type(array_list)

numpy.ndarray

In [ ]:
Yes there will be a difference in variable list and array list .
In array_list we use numpy to convert the variable list into array_list

In [36]:
num_list = [[ 1 , 2 , 3 ],[ 4 , 5 , 6 ]]

In [37]:
num_array = np.array(object = num_list)

In [38]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
l = [[ 6 , 2 , 3 , 8 ],[ 4 , 5 , 6 , 9 ]]

In [19]:
arr = np.array(l)

In [20]:
arr

array([[6, 2, 3, 8],
       [4, 5, 6, 9]])

In [23]:
arr.reshape(8,1)

array([[6],
       [2],
       [3],
       [8],
       [4],
       [5],
       [6],
       [9]])

In [24]:
arr.size

8

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [1]:
import numpy.matlib as nm

In [2]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])